astyle:ASBeautifier.o ASFormatter.o ASLocalizer.o ASResource.o ASEnhancer.o astyle_main.o
	g++ -O2 -o astyle ASBeautifier.o ASFormatter.o ASLocalizer.o ASResource.o ASEnhancer.o astyle_main.o

ASBeautifier.o:ASBeautifier.cpp
	g++ -c -o ASBeautifier.o ASBeautifier.cpp

ASFormatter.o:ASFormatter.cpp
	g++ -c -o ASFormatter.o ASFormatter.cpp

ASLocalizer.o:ASLocalizer.cpp
	g++ -c -o ASLocalizer.o ASLocalizer.cpp

ASResource.o:ASResource.cpp
	g++ -c -o ASResource.o ASResource.cpp

ASEnhancer.o:ASEnhancer.cpp
	g++ -c -o ASEnhancer.o ASEnhancer.cpp

astyle_main.o:astyle_main.cpp
	g++ -c -o astyle_main.o astyle_main.cpp
